- src/importer/components-map.js
- src/importer/create-links.js
- src/importer/importer.js
* create inner dependencies glue code **for relevant components only**.
* create public-api **for relevant components only**.
* expose inline_components to the public-api.
> Bind Action

- src/cli/commands/bind-cmd.js
- src/constants.js
- src/links-generator/links-generator.js
Fix bind command when running from the CLI.
Create public-api for the dependencies namespaces.
> fix binding dependencies when using a non-hub scope 

- src/dependency-builder/filing-cabinet/index.js
https://github.com/teambit/bit/issues/900#issuecomment-384728142
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit-javascript/52)
> adding scss to support ~

- CHANGELOG.md
- package.json
- src/index.js
- src/registry/index.js
- src/registry/registry.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit-javascript/53)
> set bit as scoped registry with bit login

- CHANGELOG.md
- package.json
- src/dependency-builder/filing-cabinet/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit-javascript/56)
> bug fix - packages on d.ts files were not recognized

- CHANGELOG.md
- package.json
- src/dependency-builder/dependency-tree/index.js
- src/dependency-builder/detectives/detective-es6/index.js
- src/dependency-builder/detectives/detective-stylable/index.js
- src/dependency-builder/detectives/detective-typescript/index.js
- src/dependency-builder/detectives/detective-vue/index.js
- src/dependency-builder/generate-tree-madge.js
- src/dependency-builder/precinct/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit-javascript/57)
> Support mixed es6 and commonjs

- CHANGELOG.md
- src/dependency-builder/generate-tree-madge.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit-javascript/58)
> fix handle tsx files when detectiveOption is empty

- CHANGELOG.md
- package.json
- src/dependency-builder/filing-cabinet/index.js
- src/dependency-builder/generate-tree-madge.js
- src/dependency-builder/precinct/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit-javascript/59)
> bug fix - .json files were not resolved correctly

- .eslintrc
- CHANGELOG.md
- fixtures/missing-deps.js
- src/constants.js
- src/dependency-builder/build-tree.js
- src/dependency-builder/build-tree.spec.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit-javascript/65)
>  avoid parsing json files as they do not contain any dependency

- package.json
- src/dependency-builder/dependency-tree/index.spec.js
- src/dependency-builder/filing-cabinet/index.spec.js
- src/package-json/package-json.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit-javascript/67)
> fix all unit tests to pass on Windows

- CHANGELOG.md
- fixtures/build-tree/a.js
- fixtures/build-tree/b.js
- fixtures/build-tree/unparsed.js
- package.json
- src/dependency-builder/build-tree.spec.js
- src/dependency-builder/dependency-tree/Config.js
- src/dependency-builder/dependency-tree/index.js
- src/dependency-builder/generate-tree-madge.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit-javascript/71)
> Bug/error "Cannot read property 'missing' of undefined"

- CHANGELOG.md
- package.json
- src/dependency-builder/dependency-tree/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit-javascript/73)
> fix get-dependency command to cache processed files

- CHANGELOG.md
- package.json
- src/dependency-builder/filing-cabinet/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit-javascript/74)
> fix symlinks to node_modules to be recognized as modules instead of files

- CHANGELOG.md
- package-lock.json
- package.json
- src/dependency-builder/detectives/detective-typescript/index.js
- src/dependency-builder/detectives/detective-typescript/index.spec.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit-javascript/80)
> support mix syntax of typescript and javascript inside .ts file

- package-lock.json
- package.json
- src/dependency-builder/detectives/detective-css-and-preprocessors/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit-javascript/82)
> fix css parsing error

- CHANGELOG.md
- package-lock.json
- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit-javascript/85)
> change typescript to be an exact version to fix the warning of mismatch version, see #1414

- CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit-javascript/87)
> changelog updates for v2

- CHANGELOG.md
- package.json
- src/dependency-builder/build-tree.spec.js
- src/dependency-builder/dependency-tree/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit-javascript/90)
> fix resolve dependencies cache to include parsing errors

- CHANGELOG.md
- package.json
- src/dependency-builder/build-tree.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit-javascript/95)
> support scoped packages when resolving package.json directory of a package

- CODE_OF_CONDUCT.md
- LICENSE
- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit-javascript/97)
> replace bitsrc.io with bit.dev

- CHANGELOG.md
- package.json
- src/cli/commands/get-dependencies.js
- src/dependency-builder/detectives/detective-es6/index.js
- src/dependency-builder/detectives/detective-es6/index.spec.js
- src/dependency-builder/detectives/detective-typescript/index.js
- src/dependency-builder/detectives/detective-typescript/index.spec.js
- src/dependency-builder/detectives/parser-helper.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit-javascript/103)
> support require statements with apostrophes

- CHANGELOG.md
- fixtures/angular/decorators/index.ts
- fixtures/angular/decorators/my-template.html
- fixtures/angular/decorators/tsconfig.json
- fixtures/angular/html-deps/another-component.ts
- fixtures/angular/html-deps/index.ts
- fixtures/angular/html-deps/main-component.ts
- fixtures/angular/html-deps/tsconfig.json
- package-lock.json
- package.json
- src/dependency-builder/build-tree.js
- src/dependency-builder/dependency-tree/Config.js
- src/dependency-builder/dependency-tree/index.js
- src/dependency-builder/generate-tree-madge.js
- src/dependency-builder/platforms/angular/extract-dependencies.js
- src/dependency-builder/platforms/angular/extract-dependencies.spec.js
- src/dependency-builder/types/dependency-tree-type.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit-javascript/104)
> identify angular components dependencies

- CHANGELOG.md
- package-lock.json
- package.json
- src/dependency-builder/platforms/angular/extract-dependencies.js
- src/dependency-builder/platforms/angular/extract-dependencies.spec.js
- show a descriptive error when `tsconfig.json` is not found.
- propagate from the component dir to find `tsconfig.json`.
- add validation for the AST of Angular files
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit-javascript/109)
> Fix issues with Angular dependencies extractions

- CHANGELOG.md
- package-lock.json
- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit-javascript/116)
> upgrade typescript and @typescript-eslint/typescript-estree packages

- package-lock.json
- package.json
- src/cli/command-registrar.ts
- src/cli/loader/loader.ts
- src/dependency-builder/build-tree.spec.ts
- src/dependency-builder/build-tree.ts
- src/dependency-builder/dependency-tree/Config.ts
- src/dependency-builder/dependency-tree/index.spec.ts
- src/dependency-builder/dependency-tree/index.ts
- src/dependency-builder/detectives/detective-css-and-preprocessors/index.ts
- src/dependency-builder/filing-cabinet/index.spec.ts
- src/dependency-builder/generate-tree-madge.ts
- src/dependency-builder/path-map.ts
- src/exceptions/index.ts
- src/exceptions/package-json-already-exists.ts
- src/exceptions/package-json-not-found.ts
- src/package-json/package-json.ts
- tsconfig.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit-javascript/122)
> Enable typescript strict mode

- CHANGELOG.md
- package-lock.json
- package.json
- src/dependency-builder/detectives/detective-es6/index.ts
- src/dependency-builder/detectives/detective-typescript/index.ts
- src/dependency-builder/detectives/parser-helper.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit-javascript/123)
> support `import { x as y }` syntax
